// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeXCbiPbPnr-vaGci0U9wka7O6qOAwQKM',
    appId: '1:332635627880:web:29a2e32723ebcc7385f6dd',
    messagingSenderId: '332635627880',
    projectId: 'ecommerceapp-a3e5e',
    authDomain: 'ecommerceapp-a3e5e.firebaseapp.com',
    databaseURL: 'https://ecommerceapp-a3e5e-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerceapp-a3e5e.firebasestorage.app',
    measurementId: 'G-VL49LFE0R4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4KtLeUuaxqOHlvWNN6h-f19NdIuReykI',
    appId: '1:332635627880:android:555ee2a33e9301b785f6dd',
    messagingSenderId: '332635627880',
    projectId: 'ecommerceapp-a3e5e',
    databaseURL: 'https://ecommerceapp-a3e5e-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerceapp-a3e5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIQe-cBn9RkquyyjBr_cMkiY-Wk8dM_q4',
    appId: '1:332635627880:ios:b9898f806343dae885f6dd',
    messagingSenderId: '332635627880',
    projectId: 'ecommerceapp-a3e5e',
    databaseURL: 'https://ecommerceapp-a3e5e-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerceapp-a3e5e.firebasestorage.app',
    androidClientId: '332635627880-7uignoe5e4clh9obnkghk3i0jc1j7vgu.apps.googleusercontent.com',
    iosClientId: '332635627880-qbd4rhpqem784iiggoflo4d51aji4k9a.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIQe-cBn9RkquyyjBr_cMkiY-Wk8dM_q4',
    appId: '1:332635627880:ios:b9898f806343dae885f6dd',
    messagingSenderId: '332635627880',
    projectId: 'ecommerceapp-a3e5e',
    databaseURL: 'https://ecommerceapp-a3e5e-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerceapp-a3e5e.firebasestorage.app',
    androidClientId: '332635627880-7uignoe5e4clh9obnkghk3i0jc1j7vgu.apps.googleusercontent.com',
    iosClientId: '332635627880-qbd4rhpqem784iiggoflo4d51aji4k9a.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

}